spring:
  application:
    name: eureka-cluster
  profiles:
    active: dev
server:
  port: 8761
 
--- 
spring:
  profiles: dev
eureka:
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

--- 
spring:
  profiles: cluster1
eureka:
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://${eureka.node2}:${server.port}/eureka/,http://${eureka.node3}:${server.port}/eureka/

--- 
spring:
  profiles: cluster2
eureka:
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://${eureka.node1}:${server.port}/eureka/,http://${eureka.node3}:${server.port}/eureka/
      
--- 
spring:
  profiles: cluster3
eureka:
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://${eureka.node1}:${server.port}/eureka/,http://${eureka.node2}:${server.port}/eureka/
